### PR TITLE
Raspberry Pi 4 (and arm64) support

### PR DESCRIPTION
**Pull request by Mrkvak**
In this pull request, there are two changes:
1) Modified Makefile to not build and burn avr binaries.
2) Updated code to work with Raspberry Pi 4 (two binaries are now created, tpiflash_rpi4 and tpiflash)

### CODE REVIEW

**Comment by cnlohr** [comment]
Why remove the .bin and burn targets from the makefile?  (that's my only question/concern)

**Comment by cnlohr** [comment]
Sorry for not getting to this til now, but with a little clarification I'd love to integrate this, @Mrkvak

**Comment by Mrkvak** [comment]
Well, make is generally used to just compile stuff. I wanted to read out a microcontroller, ran "make" expecting to compile the tpiflash binary and it overwrote the program.
It can still be compiled by running "make osccal.bin" and burned using "make burn". If you're still against it, I can partially revert that change.

**Comment by cnlohr** [comment]
I merged in just the important part of this for the BCM2711.

**Pull request closed without merging**
